services:
  cap-net-admin:
    build:
      context: ../../base
    image: container-risk-labs-toolbox:local
    container_name: crl-cap-net-admin
    command: ["sleep", "infinity"]
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
      - label=disable
    labels:
      container-risk-labs.repo: "container-risk-labs"
      container-risk-labs.scenario: "cap-net-admin"
      container-risk-labs.intent: "single-rule-cap-net-admin"
