services:
  cap-setfcap:
    build:
      context: ../../base
    image: container-risk-labs-toolbox:local
    container_name: crl-cap-setfcap
    command: ["sleep", "infinity"]
    cap_drop:
      - ALL
    cap_add:
      - SETFCAP
    security_opt:
      - no-new-privileges:true
      - label=disable
    labels:
      container-risk-labs.repo: "container-risk-labs"
      container-risk-labs.scenario: "cap-setfcap"
      container-risk-labs.intent: "single-rule-cap-setfcap"
